#!/bin/sh

rm -rf __fred*
echo > __fred1
echo > __fred2
mkdir __fred3
echo > __fred4

for file in __fred*
do
  if [ -d "$file" ]; then
    echo "skipping directory $file"
    continue
  fi
  echo file is $file
done

rm -rf __fred*
exit 0
